app/Http/routes.php
<?php
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::group(['middleware' => 'web'],function (){
	//Nothing here
});
Route::get('/', 'HomeController@index');
// LogsViewer
Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
// Login Routes...
Route::get('login', 'Auth\AuthController@getLogin');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@logout');
// Password Reset Routes...
Route::get('password/reset', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

//Grupo middleware => auth
Route::group(['middleware' => ['auth']], function ()
{
	/*
	 | API SuperAdministrator Routes
	*/
	Route::group(['middleware' => ['super.admin']], function () {
		//Usuarios
		Route::resource('usuarios', 'UserController');
	});
	/*
	 | API Administrator Routes
	*/
	Route::group(['middleware' => ['admin']], function () {
		//Users Registration Routes...
		Route::get('register', 'Auth\AuthController@getRegister');
		Route::post('register', 'Auth\AuthController@postRegister');
		//Lugares de Trabajo
		Route::resource('lugarTrabajos', 'LugarTrabajoController');
		//Instituciones
		Route::resource('instituciones', 'InstitucionController');
		//Roles
		Route::resource('roles', 'RolController');
		//Investigadores
		Route::resource('investigadores', 'InvestigadorController');
		Route::get('investigadores/{id}/historial', [ 'as' => 'investigadores.historial', 'uses' => 'InvestigadorController@historial']);
		//Historial Academico
		Route::resource('historialAcademicos', 'HistorialAcademicoController');
		//Historial Catergoria Incentivo
		Route::resource('historialIncentivos', 'HistorialIncentivoController');
		//Historial Lugar de Trabajo
		Route::resource('historialLugarTrabajos', 'historialLugarTrabajoController');
		//Historial Roles
		Route::resource('historialRoles', 'HistorialRolController');
		//Areas Tematicas
		Route::resource('areaTematicas', 'AreaTematicaController');
		//Especialidades
		Route::resource('especialidades', 'EspecialidadController');
		//Perfiles de Integrantes
		Route::resource('perfiles', 'PerfilController');
		//Tipo de Proyectos
		Route::resource('tipoProyectos', 'TipoProyectoController');
		//Proyectos
		Route::resource('proyectos', 'ProyectoController');
		//Resolucion Alta
		Route::resource('resolucionAltas', 'ResolucionAltaController');
		Route::get('autocomplete/resolucionAltas', [ 'as' => 'resolucionAltas.autocomplete', 'uses' => 'ResolucionAltaController@autocomplete']);
		//Areas de Sigeva
		Route::resource('areaSigevas', 'AreaSigevaController');
		//Integrantes
		Route::resource('integrantes', 'IntegranteController');
		//Informe de Proyectos
		Route::resource('informeProyectos', 'InformeProyectoController');
		Route::put('proyectos/{id}/informes', [ 'as' => 'informeProyectos.updateFrom', 'uses' => 'InformeProyectoController@updateFrom']);
	});
	/*
	 | API No Administrator Routes
	*/
	// Home
	Route::get('/home', 'HomeController@index');
	Route::get('contact', ['as' => 'contact.get', 'uses' => 'HomeController@getContact']);
	Route::post('contact', ['as' => 'contact.send', 'uses' => 'HomeController@postContact']);
	// Perfil de Usuario
	Route::get('/profile', ['as' => 'users.profile', 'uses' => 'UserController@profile']);
	Route::post('/profile/resetPassword', ['as' => 'users.profile.resetPassword', 'uses' => 'UserController@resetPassword']);
	Route::post('/profile/updateAvatar', ['as' => 'users.profile.updateAvatar', 'uses' => 'UserController@updateAvatar']);
	// Investigadores
	Route::resource('investigadores', 'InvestigadorController', ['only' => ['index','show']]);
	// Proyectos
	Route::resource('proyectos', 'ProyectoController', ['only' => ['index','show']]);
	// Autocompletes
	Route::get('autocomplete/investigadores', [ 'as' => 'investigadores.autocomplete', 'uses' => 'InvestigadorController@autocomplete']);
	Route::get('autocomplete/proyectos', [ 'as' => 'proyectos.autocomplete', 'uses' => 'ProyectoController@autocomplete']);
	// Reportes
	Route::get('reportes/integrantes', [ 'as' => 'reportes.integrantes', 'uses' => 'ReporteController@integrantes']);
	Route::get('reportes/integrantes/get', [ 'as' => 'reportes.integrantes.get', 'uses' => 'ReporteController@getReporteIntegrantes']);
	Route::get('reportes/proyectos', [ 'as' => 'reportes.proyectos', 'uses' => 'ReporteController@proyectos']);
	Route::get('reportes/proyectos/get', [ 'as' => 'reportes.proyectos.get', 'uses' => 'ReporteController@getReporteProyectos']);
	Route::get('reportes/proyectosActivos/get', [ 'as' => 'reportes.proyectosActivos.get', 'uses' => 'ReporteController@getReporteProyectosActivos']);
});

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
		protected $casts = [
				'id' => 'integer',
				'type' => 'boolean',
				'avatar' => 'string'
		];
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'avatar'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

		/**
		 * Validation rules
		 *
		 * @var array
		 */
		public static $rules = [
			'name' => 'required|max:255',
			'email' => 'required|email|max:255|unique:users|regex:/(.*)unrn\.edu\.ar$/i',//solo acepta dominios unrn.edu.ar
			'password' => 'required|min:6|confirmed',
			'type' => 'required',
			'avatar' => 'image|mimes:jpeg,jpg,png'
		];

		public function getHistorialIncentivos()
		{
				return $this->hasMany('App\Models\HistorialIncentivo')->orderBy('id')->get();
		}
}

app/Http/Controllers/UserController.php
<?php namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\DataTables\UserDataTable;
use App\User;
use Auth, Image, Flash, File, Validator, Hash;

class UserController extends Controller
{
		/**
		 * Create a new controller instance.
		 *
		 * @return void
		 */
		public function __construct()
		{
				$this->middleware('auth');
		}

		public function index(UserDataTable $userDataTable) {
			return $userDataTable->render('users.index');
		}

		public function create() {
			return view('auth.register');
		}

		public function store(Request $request) {
			//Nothing to here
			return view('errors.400');
		}

		public function show($id) {
			//Nothing to here
			return view('errors.400');
		}

		public function edit($id) {
			$user = User::find($id);
			if (empty($user)) {
				Flash::error('Usuario no encontrado');
				return redirect(route('usuarios.index'));
			}
			return view('users.edit')->with('user', $user);
		}

		public function profile() {
			return view('users.profile');
		}

		public function update($id, Request $request) {
			$user = User::find($id);
			if (empty($user)) {
				Flash::error('Usuario no encontrado');
				return redirect(route('usuarios.index'));
			}
			$input = $request->all();
			$user = User::where('id', $id)->update([
					'name' => $input['name'],
					'email' => $input['email'],
					'password' => ! isset($input['password']) ? $user->password : bcrypt($input['password']),
					'type' => $input['type']
			]);
			Flash::success('Usuario modificado exitosamente.');
			return redirect(route('usuarios.index'));
		}

		public function updateAvatar(Request $request) {
			//Handle the user upload of avatar
			if($request->hasFile('avatar')){
				$avatar = $request->file('avatar');
				$validator = Validator::make($request->all(), ['avatar' => 'required|image']);
				if ($validator->fails()) {
					return redirect(route('users.profile'))->withErrors($validator->errors());
				}
				$filename = time() . '.' . $avatar->getClientOriginalExtension();
				Image::make($avatar)->resize(300, 300)->save( public_path('/images/avatars/' . $filename ) );
				$user = Auth::user();
				if ($user->avatar !== 'default.jpg') {
					File::delete('images/avatars/' . $user->avatar);
				}
				$user->avatar = $filename;
				$user->save();
			}
			return redirect(route('users.profile'));
		}

		public function destroy($id) {

		}

		public function resetPassword(Request $request) {
			$user = Auth::user();
			if (! password_verify($request->password_actual, $user->password)) {
				return redirect(route('users.profile'))->withErrors(['password_actual' => 'La contraseña actual es incorrecta']);
			}
			$validator = Validator::make($request->all(), ['password' => 'required|min:6|confirmed']);
			if ($validator->fails()) {
				return redirect(route('users.profile'))->withErrors($validator->errors());
			}
			$user->password = bcrypt($request->password);
			$user->save();
			Flash::success('Contraseña modificada exitosamente.');
			Auth::logout();
			return view('auth.login');
		}
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')
  <section class="content-header">
    <h1>Usuarios</h1>
		<ol class="breadcrumb">
	    <li><a href="{{ url('/home') }}"><i class="fa fa-home"></i> Home</a></li>
	    <li><a href="{{ url('/usuarios') }}">Usuarios</a></li>
	    <li class="active">Crear</li>
	  </ol>
  </section>
  <section class="content">
    @include('adminlte-templates::common.errors')
    <div class="row">
      {!! Form::open(['route' => 'usuarios.store']) !!}

          @include('users.fields')

      {!! Form::close() !!}
    </div>
  </section>
@endsection

resources/views/users/datatables_actions.blade.php
<div class='btn-group'>
  <a href="{{ route('usuarios.edit', $id) }}" class='btn btn-success btn-xs'>
    <i class="fa fa-edit"></i>
  </a>
</div>

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
  <section class="content-header">
  	<h1>Usuarios</h1>
		<ol class="breadcrumb">
			<li><a href="{{ url('/home') }}"><i class="fa fa-home"></i> Home</a></li>
			<li><a href="{{ url('/instituciones') }}"> Usuarios</a></li>
			<li class="active">Editar</li>
		</ol>
  </section>
  <section class="content">
  	@include('adminlte-templates::common.errors')
    <div class="row">
    	{!! Form::model($user, ['route' => ['usuarios.update', $user->id], 'method' => 'patch']) !!}

        		@include('users.fields')

    	{!! Form::close() !!}
    </div>
  </section>
@endsection

resources/views/users/fields.blade.php
<div class="col-md-12">
	<div class="box box-primary">
		<div class="box-header with-border">
			<h3 class="box-title">Editar Usuario</h3>
		</div>
		<div class="box-body">
			<div class="form-group col-sm-12">
			    {!! Form::label('name', 'Nombre Completo (*):') !!}
			    {!! Form::text('name', null, ['class' => 'form-control', 'required' => 'true']) !!}
			</div>
			<div class="form-group col-sm-12">
			    {!! Form::label('email', 'Email (*):') !!}
			    {!! Form::email('email', null, ['class' => 'form-control', 'required' => 'true']) !!}
			</div>
			<div class="form-group col-sm-12">
			    {!! Form::label('password', 'Password (*):') !!}
					<div class="input-group">
						{!! Form::password('password', ['class' => 'form-control', 'disabled' => true, 'minlength' => 6, 'required' => 'true']) !!}
      			<span class="input-group-addon">
        			<input type="checkbox" id="iPass">
      			</span>
    			</div>
			</div>
			<div class="form-group col-sm-12">
			    {!! Form::label('type', 'Tipo de Usuario (*):') !!}
			    {!! Form::select('type', ['0' => 'Usuario', '1' => 'Administrador'], null, ['class' => 'form-control', 'required' => 'true']) !!}
			</div>
			<div class="form-group col-sm-12">
				<div class="checkbox icheck">
					<label><input type="checkbox" id="terminos"> Acepto los <a href="#">términos y condiciones</a></label>
				</div>
			</div>
		</div>
		<div class="box-footer" style="text-align:center;">
			{!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
			<a href="{!! route('usuarios.index') !!}" class="btn btn-default">Cancelar</a>
		</div>
	</div>
</div>
@section('scripts')
<!-- iCheck -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/skins/all.css">
<script>
    $(function () {
        $('#terminos').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            increaseArea: '20%' // optional
        });
				$('#iPass').iCheck({
            checkboxClass: 'icheckbox_minimal-blue',
            increaseArea: '15%' // optional
        });
    });
		$('#iPass').on('ifChecked', function(event){
  		$('#password').attr('disabled', false);
		});
		$('#iPass').on('ifUnchecked', function(event){
  		$('#password').attr('disabled', true);
		});
</script>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
  <section class="content-header">
    <h1>Usuarios</h1>
		<ol class="breadcrumb">
		  <li><a href="{{ url('/home') }}"><i class="fa fa-home"></i> Home</a></li>
		  <li><a href="{{ url('/usuarios') }}">Usuarios</a></li>
		  <li class="active">Listar</li>
		</ol>
  </section>
  <section class="content">
    <div class="clearfix"></div>
    @include('flash::message')
    <div class="clearfix"></div>
    <div class="box box-primary">
      <div class="box-body">
        @include('users.table')
      </div>
    </div>
  </section>
@endsection

resources/views/users/profile.blade.php
@extends('layouts.app')

@section('content')
  <section class="content-header">
    <h1>Mi Perfil</h1>
		<ol class="breadcrumb">
	    <li><a href="{{ url('/home') }}"><i class="fa fa-home"></i> Home</a></li>
	    <li class="active">Mi Perfil</li>
	  </ol>
  </section>
  <section class="content">
  	<div class="clearfix"></div>

    @include('flash::message')

    <div class="clearfix"></div>
    <div class="col-md-5">
			{!! Form::open(['route' => 'users.profile.updateAvatar', 'method' => 'post', 'enctype' => 'multipart/form-data']) !!}
			<div class="box box-primary">
        <div class="box-body box-profile">
          <img class="profile-user-img img-responsive img-circle" src="{{ url('/images/avatars/', Auth::user()->avatar) }}" alt="User profile picture">
          <h3 class="profile-username text-center">{{ Auth::user()->name }}</h3>
          <p class="text-muted text-center">{{ Auth::user()->email }}</p>
					<ul class="list-group list-group-unbordered">
            <li class="list-group-item">
							<div class="form-group has-feedback{{ $errors->has('avatar') ? ' has-error' : '' }}">
								{!! Form::hidden('_token', csrf_token()) !!}
								{!! Form::label('avatar', 'Cambiar Avatar (*):') !!}
								{{ Form::file('avatar', ['class' => 'form-control', 'required' => 'true', 'accept' => 'image/png, image/jpeg, image/jpg']) }}
								@if ($errors->has('avatar'))
									<span class="help-block">
										<strong>{{ $errors->first('avatar') }}</strong>
									</span>
								@endif
							</div>
            </li>
          </ul>
        </div><!-- /.box-body -->
				<div class="box-footer">
					{!! Form::submit('Guardar', ['class' => 'btn btn-primary btn-block']) !!}
				</div>
      </div>
			{!! Form::close() !!}
    </div>
		<div class="col-md-7">
			{!! Form::open(['route' => 'users.profile.resetPassword', 'method' => 'post']) !!}
			<div class="box box-primary">
				<div class="box-header with-border">
					<h3 class="box-title">Editar Perfil de Usuario</h3>
				</div>
				<div class="box-body">
					{!! Form::hidden('_token', csrf_token()) !!}
					<div class="form-group has-feedback{{ $errors->has('password_actual') ? ' has-error' : '' }}">
						{!! Form::label('password_actual', 'Contraseña Actual (*):') !!}
						{!! Form::password('password_actual', ['class' => 'form-control', 'minlength' => 6, 'required' => 'true']) !!}
						@if ($errors->has('password_actual'))
							<span class="help-block">
								<strong>{{ $errors->first('password_actual') }}</strong>
							</span>
						@endif
					</div>
					<div class="form-group has-feedback{{ $errors->has('password') ? ' has-error' : '' }}">
						{!! Form::label('password', 'Nueva Contraseña (*):') !!}
						{!! Form::password('password', ['class' => 'form-control', 'minlength' => 6, 'required' => 'true']) !!}
						@if ($errors->has('password'))
							<span class="help-block">
								<strong>{{ $errors->first('password') }}</strong>
							</span>
						@endif
					</div>
					<div class="form-group has-feedback{{ $errors->has('password_confirmation') ? ' has-error' : '' }}">
						{!! Form::label('password_confirmation', 'Confirmar Contraseña (*):') !!}
						{!! Form::password('password_confirmation', ['class' => 'form-control', 'minlength' => 6, 'required' => 'true']) !!}
						@if ($errors->has('password_confirmation'))
							<span class="help-block">
								<strong>{{ $errors->first('password_confirmation') }}</strong>
							</span>
						@endif
					</div>
				</div>
				<div class="box-footer">
					{!! Form::submit('Restablecer Contraseña', ['class' => 'btn btn-primary']) !!}
				</div>
			</div>
			{!! Form::close() !!}
		</div>
  </section>
@endsection

resources/views/users/table.blade.php
{!! $dataTable->table(['width' => '100%', 'class' => 'hover table table-bordered']) !!}

@section('scripts')
		<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.2.2/css/buttons.dataTables.min.css">
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
    <script src="vendor/datatables/buttons.server-side.js"></script>
    {!! $dataTable->scripts() !!}
@endsection