app/Http/routes.php
<?php
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::group(['middleware' => 'web'],function (){
	//Nothing here
});
Route::get('/', 'HomeController@index');
// LogsViewer
Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
// Login Routes...
Route::get('login', 'Auth\AuthController@getLogin');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@logout');
// Password Reset Routes...
Route::get('password/reset', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

//Grupo middleware => auth
Route::group(['middleware' => ['auth']], function ()
{
	/*
	 | API SuperAdministrator Routes
	*/
	Route::group(['middleware' => ['super.admin']], function () {
		//Usuarios
		Route::resource('usuarios', 'UserController');
	});
	/*
	 | API Administrator Routes
	*/
	Route::group(['middleware' => ['admin']], function () {
		//Users Registration Routes...
		Route::get('register', 'Auth\AuthController@getRegister');
		Route::post('register', 'Auth\AuthController@postRegister');
		//Lugares de Trabajo
		Route::resource('lugarTrabajos', 'LugarTrabajoController');
		//Instituciones
		Route::resource('instituciones', 'InstitucionController');
		//Roles
		Route::resource('roles', 'RolController');
		//Investigadores
		Route::resource('investigadores', 'InvestigadorController');
		Route::get('investigadores/{id}/historial', [ 'as' => 'investigadores.historial', 'uses' => 'InvestigadorController@historial']);
		//Historial Academico
		Route::resource('historialAcademicos', 'HistorialAcademicoController');
		//Historial Catergoria Incentivo
		Route::resource('historialIncentivos', 'HistorialIncentivoController');
		//Historial Lugar de Trabajo
		Route::resource('historialLugarTrabajos', 'historialLugarTrabajoController');
		//Historial Roles
		Route::resource('historialRoles', 'HistorialRolController');
		//Areas Tematicas
		Route::resource('areaTematicas', 'AreaTematicaController');
		//Especialidades
		Route::resource('especialidades', 'EspecialidadController');
		//Perfiles de Integrantes
		Route::resource('perfiles', 'PerfilController');
		//Tipo de Proyectos
		Route::resource('tipoProyectos', 'TipoProyectoController');
		//Proyectos
		Route::resource('proyectos', 'ProyectoController');
		//Resolucion Alta
		Route::resource('resolucionAltas', 'ResolucionAltaController');
		Route::get('autocomplete/resolucionAltas', [ 'as' => 'resolucionAltas.autocomplete', 'uses' => 'ResolucionAltaController@autocomplete']);
		//Areas de Sigeva
		Route::resource('areaSigevas', 'AreaSigevaController');
		//Integrantes
		Route::resource('integrantes', 'IntegranteController');
		//Informe de Proyectos
		Route::resource('informeProyectos', 'InformeProyectoController');
		Route::put('proyectos/{id}/informes', [ 'as' => 'informeProyectos.updateFrom', 'uses' => 'InformeProyectoController@updateFrom']);
	});
	/*
	 | API No Administrator Routes
	*/
	// Home
	Route::get('/home', 'HomeController@index');
	Route::get('contact', ['as' => 'contact.get', 'uses' => 'HomeController@getContact']);
	Route::post('contact', ['as' => 'contact.send', 'uses' => 'HomeController@postContact']);
	// Perfil de Usuario
	Route::get('/profile', ['as' => 'users.profile', 'uses' => 'UserController@profile']);
	Route::post('/profile/resetPassword', ['as' => 'users.profile.resetPassword', 'uses' => 'UserController@resetPassword']);
	Route::post('/profile/updateAvatar', ['as' => 'users.profile.updateAvatar', 'uses' => 'UserController@updateAvatar']);
	// Investigadores
	Route::resource('investigadores', 'InvestigadorController', ['only' => ['index','show']]);
	// Proyectos
	Route::resource('proyectos', 'ProyectoController', ['only' => ['index','show']]);
	// Autocompletes
	Route::get('autocomplete/investigadores', [ 'as' => 'investigadores.autocomplete', 'uses' => 'InvestigadorController@autocomplete']);
	Route::get('autocomplete/proyectos', [ 'as' => 'proyectos.autocomplete', 'uses' => 'ProyectoController@autocomplete']);
	// Reportes
	Route::get('reportes/integrantes', [ 'as' => 'reportes.integrantes', 'uses' => 'ReporteController@integrantes']);
	Route::get('reportes/integrantes/get', [ 'as' => 'reportes.integrantes.get', 'uses' => 'ReporteController@getReporteIntegrantes']);
	Route::get('reportes/proyectos', [ 'as' => 'reportes.proyectos', 'uses' => 'ReporteController@proyectos']);
	Route::get('reportes/proyectos/get', [ 'as' => 'reportes.proyectos.get', 'uses' => 'ReporteController@getReporteProyectos']);
	Route::get('reportes/proyectosActivos/get', [ 'as' => 'reportes.proyectosActivos.get', 'uses' => 'ReporteController@getReporteProyectosActivos']);
});

resources/views/instituciones/create.blade.php
@extends('layouts.app')

@section('content')
 	<section class="content-header">
    <h1>Instituciones</h1>
		<ol class="breadcrumb">
			<li><a href="{{ url('/home') }}"><i class="fa fa-home"></i> Home</a></li>
			<li><a href="{{ url('/instituciones') }}"> Instituciones</a></li>
			<li class="active">Crear</li>
		</ol>
  </section>
  <section class="content">
  	@include('adminlte-templates::common.errors')
    <div class="row">
      {!! Form::open(['route' => 'instituciones.store']) !!}

          @include('instituciones.fields')

      {!! Form::close() !!}
    </div>
  </section>
@endsection

resources/views/instituciones/edit.blade.php
@extends('layouts.app')

@section('content')
  <section class="content-header">
  	<h1>Instituciones</h1>
		<ol class="breadcrumb">
			<li><a href="{{ url('/home') }}"><i class="fa fa-home"></i> Home</a></li>
			<li><a href="{{ url('/instituciones') }}"> Instituciones</a></li>
			<li class="active">Editar</li>
		</ol>
  </section>
  <section class="content">
  	@include('adminlte-templates::common.errors')
    <div class="row">
    	{!! Form::model($institucion, ['route' => ['instituciones.update', $institucion->id], 'method' => 'patch']) !!}

        		@include('instituciones.fields')

    	{!! Form::close() !!}
    </div>
  </section>
@endsection

resources/views/instituciones/fields.blade.php
<div class="col-md-6">
	<div class="box box-primary">
			<div class="box-body">
				<div class="form-group">
						{!! Form::label('nombre', 'Nombre (*):') !!}
						{{ Form::text('nombre', null, ['class' => 'form-control', 'required' => 'true']) }}
				</div>
				<div class="form-group">
						{!! Form::label('abreviacion', 'Abreviacion (*):') !!}
						{{ Form::text('abreviacion', null, ['class' => 'form-control', 'required' => 'true']) }}
				</div>
			</div>
			<!-- Submit Field -->
			<div class="box-footer">
			{!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
			<a href="{!! route('instituciones.index') !!}" class="btn btn-default">Cancelar</a>
			</div>
	</div>
</div>

resources/views/instituciones/index.blade.php
@extends('layouts.app')

@section('content')
  <section class="content-header">
    <h1>Instituciones</h1>
		<ol class="breadcrumb">
			<li><a href="{{ url('/home') }}"><i class="fa fa-home"></i> Home</a></li>
			<li><a href="{{ url('/instituciones') }}"> Instituciones</a></li>
			<li class="active">Listar</li>
		</ol>
  </section>
  <section class="content">
		<h1 class="pull-left">
			<a class="btn btn-block btn-social btn-primary" href="{!! route('instituciones.create') !!}">
				<i class="fa fa-plus-square"></i> Nuevo
			</a>
		</h1>
  	<div class="clearfix"></div>
    @include('flash::message')
    <div class="clearfix"></div>
    <div class="box box-primary">
    	<div class="box-body">
          @include('instituciones.table')
      </div>
    </div>
  </section>
@endsection

resources/views/instituciones/show.blade.php
@extends('layouts.app')

@section('content')
  <section class="content-header">
    <h1>Instituciones</h1>
		<ol class="breadcrumb">
			<li><a href="{{ url('/home') }}"><i class="fa fa-home"></i> Home</a></li>
			<li><a href="{{ url('/instituciones') }}"> Instituciones</a></li>
			<li class="active">Mostrar</li>
		</ol>
  </section>
  <section class="content">
    <div class="box box-primary">
      <div class="box-body">
        <div class="row" style="padding-left: 20px">
          @include('instituciones.show_fields')
          <a href="{!! route('instituciones.index') !!}" class="btn btn-default">Volver</a>
        </div>
      </div>
    </div>
  </section>
@endsection

resources/views/instituciones/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $institucion->id !!}</p>
</div>


<!-- Nombre Field -->
<div class="form-group">
    {!! Form::label('nombre', 'Nombre:') !!}
    <p>{!! $institucion->nombre !!}</p>
</div>


<!-- Abreviacion Field -->
<div class="form-group">
    {!! Form::label('abreviacion', 'Abreviacion:') !!}
    <p>{!! $institucion->abreviacion !!}</p>
</div>


<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $institucion->created_at !!}</p>
</div>


<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $institucion->updated_at !!}</p>
</div>

resources/views/instituciones/table.blade.php
<table class="hover table table-bordered" id="instituciones-table">
    <thead>
        <th>Nombre</th>
        <th>Abreviacion</th>
        <th colspan="3">Acción</th>
    </thead>
    <tbody>
    @foreach($instituciones as $institucion)
        <tr>
            <td>{!! $institucion->nombre !!}</td>
            <td>{!! $institucion->abreviacion !!}</td>
            <td>
                {!! Form::open(['route' => ['instituciones.destroy', $institucion->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('instituciones.show', [$institucion->id]) !!}" class='btn btn-info btn-xs'><i class="fa fa-search"></i></a>
										@if(!Auth::guest())
	                    <a href="{!! route('instituciones.edit', [$institucion->id]) !!}" class='btn btn-success btn-xs'><i class="fa fa-edit"></i></a>
	                    {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('¿Desea eliminar la Institución?')"]) !!}
										@endif
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>
<div class="pull-right">
	{!! $instituciones->links() !!}
</div>