app/Http/routes.php
<?php
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::group(['middleware' => 'web'],function (){
	//Nothing here
});
Route::get('/', 'HomeController@index');
// LogsViewer
Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
// Login Routes...
Route::get('login', 'Auth\AuthController@getLogin');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@logout');
// Password Reset Routes...
Route::get('password/reset', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

//Grupo middleware => auth
Route::group(['middleware' => ['auth']], function ()
{
	/*
	 | API SuperAdministrator Routes
	*/
	Route::group(['middleware' => ['super.admin']], function () {
		//Usuarios
		Route::resource('usuarios', 'UserController');
	});
	/*
	 | API Administrator Routes
	*/
	Route::group(['middleware' => ['admin']], function () {
		//Users Registration Routes...
		Route::get('register', 'Auth\AuthController@getRegister');
		Route::post('register', 'Auth\AuthController@postRegister');
		//Lugares de Trabajo
		Route::resource('lugarTrabajos', 'LugarTrabajoController');
		//Instituciones
		Route::resource('instituciones', 'InstitucionController');
		//Roles
		Route::resource('roles', 'RolController');
		//Investigadores
		Route::resource('investigadores', 'InvestigadorController');
		Route::get('investigadores/{id}/historial', [ 'as' => 'investigadores.historial', 'uses' => 'InvestigadorController@historial']);
		//Historial Academico
		Route::resource('historialAcademicos', 'HistorialAcademicoController');
		//Historial Catergoria Incentivo
		Route::resource('historialIncentivos', 'HistorialIncentivoController');
		//Historial Lugar de Trabajo
		Route::resource('historialLugarTrabajos', 'historialLugarTrabajoController');
		//Historial Roles
		Route::resource('historialRoles', 'HistorialRolController');
		//Areas Tematicas
		Route::resource('areaTematicas', 'AreaTematicaController');
		//Especialidades
		Route::resource('especialidades', 'EspecialidadController');
		//Perfiles de Integrantes
		Route::resource('perfiles', 'PerfilController');
		//Tipo de Proyectos
		Route::resource('tipoProyectos', 'TipoProyectoController');
		//Proyectos
		Route::resource('proyectos', 'ProyectoController');
		//Resolucion Alta
		Route::resource('resolucionAltas', 'ResolucionAltaController');
		Route::get('autocomplete/resolucionAltas', [ 'as' => 'resolucionAltas.autocomplete', 'uses' => 'ResolucionAltaController@autocomplete']);
		//Areas de Sigeva
		Route::resource('areaSigevas', 'AreaSigevaController');
		//Integrantes
		Route::resource('integrantes', 'IntegranteController');
		//Informe de Proyectos
		Route::resource('informeProyectos', 'InformeProyectoController');
		Route::put('proyectos/{id}/informes', [ 'as' => 'informeProyectos.updateFrom', 'uses' => 'InformeProyectoController@updateFrom']);
	});
	/*
	 | API No Administrator Routes
	*/
	// Home
	Route::get('/home', 'HomeController@index');
	Route::get('contact', ['as' => 'contact.get', 'uses' => 'HomeController@getContact']);
	Route::post('contact', ['as' => 'contact.send', 'uses' => 'HomeController@postContact']);
	// Perfil de Usuario
	Route::get('/profile', ['as' => 'users.profile', 'uses' => 'UserController@profile']);
	Route::post('/profile/resetPassword', ['as' => 'users.profile.resetPassword', 'uses' => 'UserController@resetPassword']);
	Route::post('/profile/updateAvatar', ['as' => 'users.profile.updateAvatar', 'uses' => 'UserController@updateAvatar']);
	// Investigadores
	Route::resource('investigadores', 'InvestigadorController', ['only' => ['index','show']]);
	// Proyectos
	Route::resource('proyectos', 'ProyectoController', ['only' => ['index','show']]);
	// Autocompletes
	Route::get('autocomplete/investigadores', [ 'as' => 'investigadores.autocomplete', 'uses' => 'InvestigadorController@autocomplete']);
	Route::get('autocomplete/proyectos', [ 'as' => 'proyectos.autocomplete', 'uses' => 'ProyectoController@autocomplete']);
	// Reportes
	Route::get('reportes/integrantes', [ 'as' => 'reportes.integrantes', 'uses' => 'ReporteController@integrantes']);
	Route::get('reportes/integrantes/get', [ 'as' => 'reportes.integrantes.get', 'uses' => 'ReporteController@getReporteIntegrantes']);
	Route::get('reportes/proyectos', [ 'as' => 'reportes.proyectos', 'uses' => 'ReporteController@proyectos']);
	Route::get('reportes/proyectos/get', [ 'as' => 'reportes.proyectos.get', 'uses' => 'ReporteController@getReporteProyectos']);
	Route::get('reportes/proyectosActivos/get', [ 'as' => 'reportes.proyectosActivos.get', 'uses' => 'ReporteController@getReporteProyectosActivos']);
});

resources/views/especialidades/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>Especialidades</h1>
				<ol class="breadcrumb">
		      <li><a href="{{ url('/home') }}"><i class="fa fa-home"></i> Home</a></li>
		      <li><a href="{{ url('/especialidades') }}"> Especialidades</a></li>
		      <li class="active">Crear</li>
		    </ol>
    </section>
    <section class="content">
      @include('adminlte-templates::common.errors')
      <div class="row">
        {!! Form::open(['route' => 'especialidades.store']) !!}
          @include('especialidades.fields')
        {!! Form::close() !!}
      </div>
    </section>
@endsection

resources/views/especialidades/datatables_actions.blade.php
{!! Form::open(['route' => ['especialidades.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('especialidades.edit', $id) }}" class='btn btn-success btn-xs'>
        <i class="fa fa-edit"></i>
    </a>
    {!! Form::button('<i class="fa fa-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/especialidades/edit.blade.php
@extends('layouts.app')

@section('content')
  <section class="content-header">
    <h1>Especialidades</h1>
		<ol class="breadcrumb">
	    <li><a href="{{ url('/home') }}"><i class="fa fa-home"></i> Home</a></li>
	  	<li><a href="{{ url('/especialidades') }}"> Especialidades</a></li>
		  <li class="active">Editar</li>
		</ol>
  </section>
  <section class="content">
    @include('adminlte-templates::common.errors')
    <div class="row">
      {!! Form::model($especialidad, ['route' => ['especialidades.update', $especialidad->id], 'method' => 'patch']) !!}
        @include('especialidades.fields')
      {!! Form::close() !!}
    </div>
  </section>
@endsection

resources/views/especialidades/fields.blade.php
<div class="col-md-6">
	<div class="box box-primary">
		<div class="box-body">
			<!-- Nombre Field -->
			<div class="form-group">
			    {!! Form::label('nombre', 'Nombre (*):') !!}
			    {!! Form::text('nombre', null, ['class' => 'form-control', 'required' => 'true']) !!}
			</div>
			<div class="form-group">
					{!! Form::label('area_tematica_id', 'Área Temática (*):') !!}
					{{ Form::select('area_tematica_id', $tematicas, null, ['class' => 'form-control', 'placeholder' => 'Seleecionar un Área', 'required' => 'true']) }}
			</div>
			<!-- Submit Field -->
			<div class="form-group">
			    {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
			    <a href="{!! route('especialidades.index') !!}" class="btn btn-default">Cancelar</a>
			</div>
		</div>
	</div>
</div>

resources/views/especialidades/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>Especialidades</h1>
				<ol class="breadcrumb">
		      <li><a href="{{ url('/home') }}"><i class="fa fa-home"></i> Home</a></li>
		      <li><a href="{{ url('/especialidades') }}"> Especialidades</a></li>
		      <li class="active">Listar</li>
		    </ol>
    </section>
    <section class="content">
      <div class="clearfix"></div>
      @include('flash::message')
      <div class="clearfix"></div>
			<div class="row">
				<div class="col-md-12">
					<div class="box box-primary">
						<div class="box-header with-border">
							<h3 class="box-title">Listar</h3>
						</div>
						<div class="box-body">
							@include('especialidades.table')
						</div>
					</div>
				</div>
			</div>
    </section>
@endsection

resources/views/especialidades/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>Especialidad</h1>
				<ol class="breadcrumb">
			    <li><a href="{{ url('/home') }}"><i class="fa fa-home"></i> Home</a></li>
			  	<li><a href="{{ url('/especialidades') }}"> Especialidades</a></li>
				  <li class="active">Mostrar</li>
				</ol>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('especialidades.show_fields')
                    <a href="{!! route('especialidades.index') !!}" class="btn btn-default">Volver</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/especialidades/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $especialidad->id !!}</p>
</div>

<!-- Nombre Field -->
<div class="form-group">
    {!! Form::label('nombre', 'Nombre:') !!}
    <p>{!! $especialidad->nombre !!}</p>
</div>

resources/views/especialidades/table.blade.php
{!! $dataTable->table(['width' => '100%', 'class' => 'hover table table-bordered']) !!}

@section('scripts')
		<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.2.2/css/buttons.dataTables.min.css">
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
    <script src="vendor/datatables/buttons.server-side.js"></script>
    {!! $dataTable->scripts() !!}
@endsection